### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by noelthekk**
Adding LICENSE file to patches directory

Adding missing LICENSE to the patches directory to address https://github.com/ZOSOpenTools/meta/issues/103

### CODE REVIEW

**Comment by IgorTodorovskiIBM** [comment]
@NFuture , I noticed your PRs are getting closed. Is this intended?

**Comment by noelthekk** [comment]
No. I am not sure as why this is.

**Comment by noelthekk** [comment]
I have reopened the PR's

**Review by IgorTodorovskiIBM — COMMENTED** [review]
LGTM

**Comment by IgorTodorovskiIBM** [comment]
It closed, I assume this is the reason: 
> closed this by deleting the head repository [last week](https://github.com/ZOSOpenTools/autoconfport/pull/45#event-11002000016)

**Pull request closed without merging**
